### ISSUE TITLE
Doesn't load stories in SFOS 3.4.

### ISSUE THREAD

**Issue by poetaster** [neversun/sailfish-hackernews#6]
I tried on a Volla phone and a Fairphone 2. 

If you're not maintaining, I can take over. I built a quick and dirty HN viewer (on the openrepos site).

**Comment by neversun** [comment]
I will have a look into it. 
I hope there is just a small change needed because of the updated Browser/Webkit component (if this backfires to the QML side too (SilicaWebView))

**Comment by neversun** [comment]
I fixed someissues with Sailfish 3.4/python 3.7 and submitted a new version to the Harbour/store.

Thanks for reaching out!
